### ISSUE TITLE
複数のファイルを対象に実行したい

### ISSUE THREAD

**Issue by Shotaro-Yoshinaga** [forno/HHMCoordinateConverter#4]
複数のファイルを対象にして同時に行う場合でも，教えていただいた方法で可能ということでしょうか？

**Comment by forno** [comment]
複数のファイルを対象にする #とは

1. 複数の入力を使う
2. 複数の出力を使う

のどちらでしょうか

1であれば，シェルのパイプラインを使いましょう

```bash
cat file1 file2 | ./build/converter --config config/Cooking > converted/1_162.csv
```

2であれば，ちょっとどういう要件かわかりませんが，ファイルを作ってから分割すればいいのではないでしょうか


または，別の入力から別の出力を作るということであれば
入力と出力をそれぞれ変更すればよいと思います

```bash
./build/converter --config config/Cooking < input_file.csv > outfile.csv
```

**Comment by forno** [comment]
このあたりの取り回しに関しては

- シェル
- コマンド
- パイプライン
- リダイレクト

あたりで検索してくださいませ

**Comment by forno** [comment]
たくさんのファイルを変換したいということであれば，
例えば

```bash
find -f src/ -exec ./build/converter --config config/Cooking < src/'{}' > converted/'{}'.csv
```

みたいな感じ？とか
シェルスクリプトでループを書いて回すと良いと思います

**Comment by forno** [comment]
@Shotaro-Yoshinaga 問題が解決したらCloseしてください～

**Comment by Shotaro-Yoshinaga** [comment]
1であれば，シェルのパイプラインを使いましょう
```
cat file1 file2 | ./build/converter --config config/Cooking > converted/1_162.csv
```
の場合ですが，これは
file1，file2それぞれで計算が行われているということで正しいでしょうか？

**Comment by forno** [comment]
> file1，file2それぞれで計算が行われているということで正しいでしょうか？

違うよ

**Comment by forno** [comment]
再掲しますが

>または，別の入力から別の出力を作るということであれば
> 入力と出力をそれぞれ変更すればよいと思います
> 
> ```bash
> ./build/converter --config config/Cooking < input_file.csv > outfile.csv
> ```

**Comment by Shotaro-Yoshinaga** [comment]
すみません．
確認不足でした．
ありがとうございました．
